# Site settings
author: Annalisa Graziano
title: Annalisa Codes
header-img: img/home-bg.png
email: arosegraz@gmail.com
copyright_name: Annalisa Graziano
description: > # this means to ignore newlines until "baseurl:"
  School and personal projects
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  annalisarose

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
